server:
  port: 8888
spring:
  application:
    name: nursing
  datasource:
    url: jdbc:mysql://localhost:3306/flight?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath:mapper/*.xml
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs